spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gobang?characterEncoding=utf-8
    username: root
    password: qrx123000
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml
server:
  port: 8081
